# Header
menu:
  HOME: /
  PROJECTS: /projects
  ABOUT: /about
  ARCHIVES: /archives
rss: /atom.xml

# Content
excerpt_link: Read More

widgets:
# - category
# - tag
# - tagcloud
- recent_posts
- archive


# widget behavior
archive_type: 'monthly'
show_count: false
archive_style: list

# Miscellaneous
# google_analytics:
google_webbaster: '<meta name="google-site-verification" content="N3tLo4DkemKMc6DXU9pIfh9auQjhV7DolwbTGfY_Ejo" />
'
# gauges_analytics:
# favicon: /favicon.png
# twitter:
# google_plus:
# fb_admins:
# fb_app_id:

social:
  - icon: '<img width="32" width="32" src="https://unpkg.com/simple-icons@latest/icons/github.svg" />'
    url: 'https://github.com/satyamyadav'
  - icon: '<img width="32" width="32" src="https://unpkg.com/simple-icons@latest/icons/linkedin.svg" />'
    url: 'https://www.linkedin.com/in/satyamyadav3/'
  - icon: '<img width="32" width="32" src="https://unpkg.com/simple-icons@latest/icons/twitter.svg" />'
    url: 'https://twitter.com/'

language: en


# base style css
style: https://satyamyadav.github.io/stylesimple/dist/hexo/hexo.css

# class list 


# Sidebar : left | right | none
sidebar: none

# classes 
#container => bootstrap container : container | container-fluid
classes:
  postCard: 'border-0 pb-5'
  container: 'container pl-md-5 pr-md-5'
  sidebar: 'col-12 col-md-3'
  feed: 'col-12 col-md-9'
  nav: 'navbar navbar-expand navbar-light bg-light fixed-top'

# icons
icons:
  share: '<img width="22" width="22" src="https://unpkg.com/react-material-icon-svg@1.4.0/svg/share-variant.svg" />'
  comment: '<img width="22" width="22" src="https://unpkg.com/react-material-icon-svg@1.4.0/svg/comment-text-outline.svg" />'
  github: '<img width="22" width="22" src="https://unpkg.com/simple-icons@latest/icons/github.svg" />'
  view: '<img width="22" width="22" src="https://unpkg.com/react-material-icon-svg@1.4.0/svg/eye.svg" />'