# Header
menu:
  Home: /
  Portfolio: /projects
  About: /about
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

widgets:
# - category
# - tag
# - tagcloud
- recent_posts
- archive


# widget behavior
archive_type: 'monthly'
show_count: false
archive_style: list

# Miscellaneous
# google_analytics:
# gauges_analytics:
# favicon: /favicon.png
# twitter:
# google_plus:
# fb_admins:
# fb_app_id:

social:
  - icon: '<img width="32" width="32" src="https://unpkg.com/simple-icons@latest/icons/github.svg" />'
    url: 'https://github.com/satyamyadav'
  - icon: '<img width="32" width="32" src="https://unpkg.com/simple-icons@latest/icons/linkedin.svg" />'
    url: 'https://www.linkedin.com/in/satyamyadav3/'
  - icon: '<img width="32" width="32" src="https://unpkg.com/simple-icons@latest/icons/twitter.svg" />'
    url: 'https://twitter.com/'

language: en


# base style css
style: https://satyamyadav.github.io/stylesimple/dist/material/material.css
icons: 

# class list 


# Sidebar : left | right | none
sidebar: right

# classes 
#container => bootstrap container : container | container-fluid
classes:
  postCard: 'border-0 pb-5'
  container: 'container'
  sidebar: 'col-12 col-md-3'
  feed: 'col-12 col-md-9'