# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

banner: true

card_class: 'border-0 pb-5'

#container => bootstrap container : container | container-fluid
container: 'container'

# Sidebar : left | right | none
sidebar: right
sidebarClass: col-3
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: false
archive_style: list

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

language: en


# base style css
style: https://satyamyadav.github.io/stylesimple/dist/material/material.css
